WebUI/Models/BooksListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get
            {
                return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
            }
        }
    }
}

WebUI/Controllers/BooksController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 4;
        public BooksController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository
                .Books.Where(b => genre == null || b.Genre == genre)
                .OrderBy(book => book.BookId)
                .Skip((page - 1) * pageSize).Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ? repository.Books.Count() : repository.Books.Where(book => book.Genre == genre).Count()
                },
                CurrentGenre = genre
            };

            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }



        public RedirectToRouteResult AddToCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
            .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                cart.AddItem(book,1);
             }

            return RedirectToAction("Index", new { returnUrl });

        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
            .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                cart.RemoveLine(book);
            }

            return RedirectToAction("Index", new { returnUrl });

        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if(cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Cart is epty!");
            }
            if(ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(new ShippingDetails());
            }

        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;
            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(genres);
        }
    }
}

WebUI/Views/Books/List.cshtml
@using WebUI.Models
@model BooksListViewModel

@{
    ViewBag.Title = "Books";
}

@foreach(var book in Model.Books)
{
    @Html.Partial("_BookSummary", book)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, genre = Model.CurrentGenre}))
</div>

WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "ORDER";
}

<h2>ORDER</h2>
<p> enter your contact information</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <div class="form-group">
        <label>Name</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })

    </div>
    <h3>ADDRESS</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>
                    @(property.DisplayName ?? property.PropertyName)
                </label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })

            </div>
        }
    }


    <h3>DELIVERY</h3>
    <div class="form-group">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Courier delivery

        </label>
        

    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="OK" />

    </div>
}

WebUI/Views/Cart/Completed.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Order";
}

<h2>Thanks</h2>
<p>Your order: 360$</p>

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "BOOKSHOP CART";
}

<h2>@ViewBag.Title</h2>

<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Count</th>
            <th>Title</th>
            <th class="text-right">Price</th>
            <th class="text-right">Sum</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-left">@line.Quantity</td>
            <td class="text-left">@line.Book.Title</td>
            <td class="text-right">@line.Book.Price.ToString("#$")</td>
            @*<td class="text-right">360$</td>*@
            <td class="text-right">@((line.Quantity * line.Book.Price).ToString("#$"))</td>
        @*<td class="text-right">360$</td>*@
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("BookId", line.Book.BookId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="Delete" />
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Sum</td>
            @*<td class="text-right">@Model.Cart.ComputeTotalvalue().ToString("#$")</td>*@
        @*<td class="text-right">360$</td>*@
        </tr>

    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Back</a>
    @Html.ActionLink("Order", "checkout", null, new { @class= "btn btn-primary"})

</div>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Order", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery},
    new { @class = "btn btn-default navbar-btn"})
</div>

<div class="navbar-text navbar-right">
    <b>CART</b>
    @Model.Lines.Sum(x=> x.Quantity) book,
    @Model.ComputeTotalvalue().ToString("#$")

</div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Books", null, new {  @class = "btn btn-block btn-default btn-lg"})


@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Books",
    acrion = "List",
    genre = link,
    page = 1


}, new
{
    @class = "btn btn-block btn-default btn-lg"
    + (link == ViewBag.SelectedGenre ? "btn-primary" : "")
})
}

WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book


<div class="well">
    <div class="row">
        <div class="col-xs-10">
            <h3>
                @Model.Title
            </h3>
            <h4>
                @Model.Subtitle
            </h4>

        </div>
        <div class="col-xs-2">
            <h3>
                <strong id="price" class="pull-right label label-primary"> @Model.Price.ToString("#$")</strong>
            </h3>

            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.BookId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Add to cart" />
                </div>
            }
            <input type="text" class="form-control" value="" />

        </div>

    </div>
    <span class="lead">@Model.Genre</span>
</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left:15px;
        }
    </style>

    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation" >
        <a class="navbar-brand" href="#">BOOKSHOP</a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="genres" class="col-xs-3">
            @Html.Action("Menu", "Nav")
        </div>
        <div id="genres" class="col-xs-2">
        </div>
        <div class="col-xs-6">
            @RenderBody()
        </div>

    </div>
   

   

</body>
</html>